[package]
name = "salvo_issue"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
salvo = { version = "0.44.1", features = ["oapi"] }
tokio = { version = "1", features = ["macros"] }
